// ACTIONS FOR CARS
export const GET_FILTERED_CARS = "GET_FILTERED_CARS";
export const CARS_ERROR = "CARS_ERROR";

// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
